// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Deedle")>]
[<assembly: AssemblyProductAttribute("Deedle")>]
[<assembly: AssemblyDescriptionAttribute("Easy to use .NET library for data manipulation and scientific programming")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.0-beta01")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Deedle"
    let [<Literal>] AssemblyProduct = "Deedle"
    let [<Literal>] AssemblyDescription = "Easy to use .NET library for data manipulation and scientific programming"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyInformationalVersion = "2.0.0-beta01"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
