// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Deedle")>]
[<assembly: AssemblyProductAttribute("Deedle")>]
[<assembly: AssemblyDescriptionAttribute("Easy to use .NET library for data manipulation and scientific programming")>]
[<assembly: AssemblyVersionAttribute("1.2.5")>]
[<assembly: AssemblyFileVersionAttribute("1.2.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Deedle"
    let [<Literal>] AssemblyProduct = "Deedle"
    let [<Literal>] AssemblyDescription = "Easy to use .NET library for data manipulation and scientific programming"
    let [<Literal>] AssemblyVersion = "1.2.5"
    let [<Literal>] AssemblyFileVersion = "1.2.5"
