// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Deedle.Excel")>]
[<assembly: AssemblyProductAttribute("Deedle.Excel")>]
[<assembly: AssemblyDescriptionAttribute("Deedle integration with Excel")>]
[<assembly: AssemblyVersionAttribute("2.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.2.0")>]
[<assembly: AssemblyFileVersionAttribute("2.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Deedle.Excel"
    let [<Literal>] AssemblyProduct = "Deedle.Excel"
    let [<Literal>] AssemblyDescription = "Deedle integration with Excel"
    let [<Literal>] AssemblyVersion = "2.2.0"
    let [<Literal>] AssemblyInformationalVersion = "2.2.0"
    let [<Literal>] AssemblyFileVersion = "2.2.0"
