// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Deedle.Interactive")>]
[<assembly: AssemblyProductAttribute("Deedle.Interactive")>]
[<assembly: AssemblyDescriptionAttribute("Deedle Formatting extensions for dotnet interactive")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Deedle.Interactive"
    let [<Literal>] AssemblyProduct = "Deedle.Interactive"
    let [<Literal>] AssemblyDescription = "Deedle Formatting extensions for dotnet interactive"
    let [<Literal>] AssemblyVersion = "3.0.0"
    let [<Literal>] AssemblyInformationalVersion = "3.0.0"
    let [<Literal>] AssemblyFileVersion = "3.0.0"
