// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Deedle.Math")>]
[<assembly: AssemblyProductAttribute("Deedle.Math")>]
[<assembly: AssemblyDescriptionAttribute("Deedle interop with Math.Net")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Deedle.Math"
    let [<Literal>] AssemblyProduct = "Deedle.Math"
    let [<Literal>] AssemblyDescription = "Deedle interop with Math.Net"
    let [<Literal>] AssemblyVersion = "3.0.0"
    let [<Literal>] AssemblyInformationalVersion = "3.0.0"
    let [<Literal>] AssemblyFileVersion = "3.0.0"
