// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Deedle.Math")>]
[<assembly: AssemblyProductAttribute("Deedle.Math")>]
[<assembly: AssemblyDescriptionAttribute("Deedle interop with Math.Net")>]
[<assembly: AssemblyVersionAttribute("2.4.1")>]
[<assembly: AssemblyInformationalVersionAttribute("2.4.1")>]
[<assembly: AssemblyFileVersionAttribute("2.4.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Deedle.Math"
    let [<Literal>] AssemblyProduct = "Deedle.Math"
    let [<Literal>] AssemblyDescription = "Deedle interop with Math.Net"
    let [<Literal>] AssemblyVersion = "2.4.1"
    let [<Literal>] AssemblyInformationalVersion = "2.4.1"
    let [<Literal>] AssemblyFileVersion = "2.4.1"
