<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Deedle.VirtualPreservation</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Common/FsUnit.fs">
      <Link>FsUnit.fs</Link>
    </Compile>
    <Compile Include="../Deedle.Tests/VirtualInstrumentation.fs">
      <Link>VirtualInstrumentation.fs</Link>
    </Compile>
    <Compile Include="Program.fs" />
    <None Include="paket.references" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Deedle\Deedle.fsproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
