name: Build and Test PR

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore .NET local tools
        run: dotnet tool restore
      - name: Restore packages
        run: dotnet paket restore
      - name: Build and test
        run: .\build.ps1
        shell: pwsh

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore .NET local tools
        run: dotnet tool restore
      - name: Restore packages
        run: dotnet paket restore
      - name: Build and test
        run: ./build.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          force_orphan: true
      - name: Obtain NuGet key
        # this hash is v1.1.0
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544
        id: login
        with:
            user: dsyme
      - name: Publish NuGets (if this version not published before)
        run: dotnet nuget push ./bin/*.nupkg -s https://www.nuget.org/api/v2/package -k ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate
